name: pin_code_fields

packages:
  - packages/pin_code_fields
  - packages/pin_code_fields/example

scripts:
  analyze:
    run: melos exec -- flutter analyze
    description: Run flutter analyze in all packages

  test:
    run: melos exec --scope="pin_code_fields" -- flutter test
    description: Run flutter test in pin_code_fields package

  format:
    run: melos exec -- dart format .
    description: Format all packages

  format:check:
    run: melos exec -- dart format --set-exit-if-changed .
    description: Check formatting in all packages

  publish:dry-run:
    run: melos exec --scope="pin_code_fields" -- flutter pub publish --dry-run
    description: Dry run publish for pin_code_fields package

  publish:
    run: melos exec --scope="pin_code_fields" -- flutter pub publish
    description: Publish pin_code_fields package to pub.dev
