name: pin_code_fields

packages:
  - packages/pin_field_core
  - packages/pin_field_material
  - packages/example

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: melos exec -- flutter analyze
    description: Run flutter analyze in all packages

  test:
    run: melos exec -- flutter test
    description: Run flutter test in all packages

  format:
    run: melos exec -- dart format .
    description: Format all packages

  format:check:
    run: melos exec -- dart format --set-exit-if-changed .
    description: Check formatting in all packages

  publish:dry-run:
    run: melos exec -- flutter pub publish --dry-run
    description: Dry run publish for all packages
